countries = [
        'united states', 'india', 'ireland', 'united kingdom', 'germany',
        'finland', 'france', 'sweden', 'nan', 'netherlands', 'switzerland',
        'china', 'canada', 'spain', 'brazil', 'saudi arabia',
        'australia', 'turkey', 'czechia', 'united arab emirates',
        'south korea', 'singapore', 'south africa', 'mexico', 'taiwan',
        'japan', 'belgium', 'italy', 'colombia', 'algeria',
        'norway', 'qatar', 'venezuela', 'indonesia', 'malaysia',
        'denmark', 'luxembourg', 'hong kong', 'philippines',
        'austria', 'chile'
    ]

country_choices = [(country, country.title()) for country in countries]


industries = ['information technology and services', 'military', 'accounting', 'retail', 'computer software', 'telecommunications', 'defense & space', 'financial services',
              'management consulting', 'banking', 'internet', 'consumer electronics', 'electrical/electronic manufacturing', 'public policy', 'government administration',
              'restaurants', 'hospital & health care', 'aviation & aerospace', 'automotive', 'semiconductors', 'computer networking', 'food & beverages', 'oil & energy',
              'transportation/trucking/railroad', 'pharmaceuticals', 'consumer goods', 'design', 'education management', 'insurance', 'photography', 'logistics and supply chain',
              'publishing', 'real estate', 'translation and localization', 'facilities services', 'investment banking', 'cosmetics', 'human resources', 'medical devices', 'biotechnology',
              'mechanical or industrial engineering', 'broadcast media', 'hospitality', 'sporting goods', 'chemicals', 'airlines/aviation', 'commercial real estate', 'construction', 'security and investigations',
              'supermarkets', 'health, wellness and fitness', 'food production', 'civil engineering', 'medical practice', 'media production', 'machinery', 'utilities', 'textiles', 'research', 'package/freight delivery', 'mining & metals',
              'mental health care', 'outsourcing/offshoring', 'professional training & coaching', 'entertainment', 'information services', 'international affairs', 'wireless', 'writing and editing', 'building materials',
              'higher education', 'law practice', 'computer hardware', 'tobacco', 'railroad manufacture', 'international trade and development', 'public relations and communications', 'non-profit organization management',
              'printing', 'staffing and recruiting', 'environmental services', 'capital markets', 'farming', 'business supplies and equipment', 'primary/secondary education', 'legislative office', 'industrial automation',
              'wine and spirits', 'paper & forest products', 'leisure, travel & tourism', 'arts and crafts', 'packaging and containers', 'marketing and advertising', 'civic & social organization',
              'apparel & fashion', 'individual & family services', 'music', 'motion pictures and film', 'graphic design', 'luxury goods & jewelry', 'renewables & environment', 'legal services',
              'consumer services', 'law enforcement', 'philanthropy', 'wholesale', 'glass, ceramics & concrete', 'judiciary']

industry_choices = [(industry, industry.title()) for industry in industries]

states = ['new york', 'maharashtra', 'dublin', 'virginia', 'greater london', 'california', 'new jersey', 'wisconsin', 'washington', 'texas', 'karnataka', 'north carolina',
          'district of columbia', 'bavaria', 'uusimaa', 'île-de-france', 'aquitaine', 'illinois', 'stockholm', 'west berkshire', 'michigan', 'minnesota', 'zuid-holland',
          'uttar pradesh', 'georgia', 'vaud', 'guangdong', 'hillingdon', 'maryland', 'zurich', 'basel-city', 'kentucky', 'nordrhein-westfalen', 'ontario', 'connecticut', 'surrey',
          'ohio', 'massachusetts', 'hessen', 'turin', 'south carolina', 'quebec', 'rhode island', 'ile-de-france', 'buckinghamshire', 'madrid', 'rio de janeiro', 'edinburgh',
          'oregon', 'rheinland-pfalz', 'bayern', 'pennsylvania', 'kansas', 'eastern province', 'west sussex', 'stockholms lan', 'victoria', 'skåne', 'indiana', 'england', 'istanbul',
          'sao paulo', 'missouri', 'centre', 'hertfordshire', 'tennessee', 'praha', 'dubai', "seoul-t'ukpyolsi", 'gauteng', 'new hampshire', 'alberta', 'new south wales',
          'distrito federal', 'delaware', 'schwyz', 'north rhine-westphalia', 'basque country', 'florida', "t'ai-pei", 'kanagawa', 'louisiana', 'brussels hoofdstedelijk gewest',
          'noord-holland', 'sandwell', 'geneva', 'federal district', 'vasternorrlands lan', 'ar riyāḑ', 'northholland', 'milan', 'corrèze', 'utrecht', 'andhra pradesh', 'paris',
          'lombardy', 'noord-brabant', 'hauts-de-france', 'galicia', 'haryana', 'tokyo', 'medway', 'hampshire', 'beijing', 'aberdeen city', "provence-alpes-cote d'azur",
          'distrito especial', 'queensland', 'berlin', 'colorado', 'lazio', 'alger', 'catalonia', 'piedmont', 'arizona', 'rogaland', 'ad dawhah', 'iowa', 'akershus', 'capital',
          'hesse', 'vlaams-brabant', 'british columbia', 'warwickshire', 'kirklees', 'london', 'alabama', 'latium', 'arkansas', 'liberecky kraj', 'hauts-de-seine', 'abu dhabi',
          'jakarta raya', 'hordaland', 'kuala lumpur', 'vaestra goetaland', 'leinster', 'west virginia', 'hovedstaden', 'idaho', 'nuevo león', 'oklahoma', 'utah', 'sabah', 'nebraska',
          'nevada', 'newcastle upon tyne', 'niedersachsen', 'mato grosso', 'rio grande do sul', 'central and western district', 'hawaii', 'midtjylland', 'metro manila', 'salzburg',
          'oxfordshire', 'belfast', 'basilicate', 'worcestershire', 'nuevo leon', 'capital region', 'manchester', 'nottingham', 'delhi', 'santiago metropolitan', 'auvergne-rhône-alpes']

state_choices = [(state, state.title()) for state in states]

cities = [
    'new york', 'bombay', 'dublin', 'alexandria', 'london', 'palo alto',
    'teaneck', 'withee', 'redmond', 'dallas', 'randolph', 'san francisco',
    'bangalore', 'charlotte', 'washington', 'seattle', 'cupertino', 'munich',
    'redwood shores', 'espoo', 'paris', 'france', 'mountain view',
    'oak brook', 'kista', 'chicago', 'berks', 'oakland', 'dearborn',
    'santa clara', 'san jose', 'detroit', 'purchase', 'minneapolis',
    'the hague', 'noida', 'atlanta', 'vevey', 'shenzhen', 'round rock',
    'hayes', 'morristown', 'houston', 'bethesda', 'zurich', 'basel',
    'new brunswick', 'erlanger', 'bloomington', 'bonn', 'toronto',
    'fairfield', 'guildford', 'cincinnati', 'deerfield', 'austin',
    'mooresville', 'hopkinton', 'pune', 'basking ridge', 'frankfurt',
    'montvale', 'menlo park', 'falls church', 'turin', 'roseland',
    'illinois city', 'san ramon', 'none', 'montréal', 'woonsocket',
    'bezons', 'buckingham', 'kenilworth', 'boadilla del monte', 'milwaukee',
    'northbrook', 'rio de janeiro', 'madrid', 'saint paul', 'norwalk',
    'los angeles', 'boston', 'irving', 'bellevue', 'edinburgh',
    'beaverton', 'ludwigshafen', 'richfield', 'fort worth', 'od',
    'pittsburgh', 'overland park', 'dhahran', 'crawley', 'arlington',
    'mclean', 'boulogne-billancourt', 'stockholm', 'melbourne',
    'san diego', 'malmö', 'wayzata', 'addison', 'philadelphia',
    'peoria heights', 'pasadena', 'waltham', 'indianapolis',
    'plainsboro', 'maslak', 'sao paulo', 'kansas city',
    'saint-denis-de-palin', 'baltimore', 'issaquah', 'hertfordshire',
    'danbury', 'midland', 'providence', 'memphis', 'st. louis',
    'ingelheim', 'prague', 'burbank', 'dubai', 'seoul', 'cleveland',
    'columbus', 'johannesburg', 'rochester', 'moline', 'hartford',
    'hillsborough', 'edmonton', 'sydney', 'erlangen', 'herzogenaurach',
    'mexico', 'nashville', 'wilmington', 'hoffman estates', 'jona',
    'menomonee falls', 'louisville', 'duluth', 'madison', 'leverkusen',
    'north sydney', 'bilbao', 'ann arbor', 'jacksonville', 'panchiao',
    'denham', 'schenectady', 'newtown', 'plano', 'osasco', 'marlborough',
    'morrisville', 'yokohama', 'monroe', 'brussels', 'thousand oaks',
    'amsterdam', 'chesterfield', 'north chicago', 'sandwell', 'geneva',
    'schindellegi', 'seminole', 'brasília', 'alcobendas', 'kalamazoo',
    'ase', 'lakeland', 'san bruno', 'riyadh', 'san antonio',
    'bloomfield', 'newark', 'san donato milanese', 'garfield',
    'university park', 'ferrand', 'utrecht', 'ada', 'glattbrugg',
    'winston salem', 'sunrise', 'nanterre', 'cary', 'hyderabad',
    'saint denis', 'troy', 'sandton', 'gainesville', 'st paul',
    'de pere', 'milano', 'noord', 'bay village', 'pleasanton',
    'aurora', 'lake buena vista', 'lille', 'framingham', 'nassau',
    'arteixo', 'torrance', 'stanford', 'gurgaon', 'tokyo',
    'south san francisco', 'gillingham', 'hook', 'franklin lakes',
    'peking', 'berwyn', 'aberdeen', 'hanover', 'meyreuil',
    'bogota', 'brisbane', 'raritan', 'berlin', 'chester',
    'stamford', 'denver', 'st. petersburg', 'rome', 'algiers',
    'barcelona', 'southfield', 'essen', 'college station', 'tempe',
    'stavanger', 'brookfield', 'east lansing', 'doha', 'cedar rapids',
    'boca raton', 'fornebu', 'riverside', 'hoofddorp', 'caracas',
    'cambridge', 'albany', 'chevy chase', 'englewood', 'battle creek',
    'frankfurt am main', 'west lafayette', 'leuven', 'renton',
    'champaign', 'benton harbor', 'levis', 'vancouver', 'harrisburg',
    'sacramento', 'valley forge', 'reston', 'dusseldorf', 'west yorkshire',
    'chertsey', 'farmington hills', 'fort bragg', 'birmingham',
    'akron', 'des moines', 'berkeley', 'bentonville',
    'nove mesto pod smrkem', 'blue bell', 'miami', 'hull', 'phoenix',
    'la defense', 'buffalo', 'warwick', 'majadahonda', 'abu dhabi',
    'epsom', 'jakarta', 'amstelveen', 'akre', 'kuala lumpur',
    'reynoldsburg', 'göteborg', 'monrovia', 'lake success',
    'coolock', 'irvine', 'brabant', 'goodlettsville', 'ithaca',
    'andover', 'copenhagen', 'nord', 'college park', 'la jolla',
    'veldhoven', 'boise', 'malvern', 'davis', 'lansing',
    'san pedro garza garcía', 'east hartford', 'clayton',
    'tinker afb', 'murray', 'ottawa', 'the woodlands', 'calgary',
    'pitas', 'milan', 'omaha', 'springdale', 'las vegas',
    'helsinki', 'newcastle upon tyne', 'tucson', 'fremont',
    'wolfsburg', 'lake forest', 'schaumburg', 'warsaw',
    'sunnyvale', 'bau', 'royal oak', 'holzkirchen', 'eden prairie',
    'porto alegre', 'hong kong', 'honolulu', 'chapel hill',
    'rosemont', 'orange', 'evanston', 'montrouge', 'neubiberg',
    'surrey', 'naples', 'darmstadt', 'orlando', 'arhus',
    'tampa', 'fort collins', 'parkville', 'lehi', 'raleigh',
    'north canton', 'monheim am rhein', 'pasig city', 'silver spring',
    'aliso viejo', 'bridgewater', 'new britain', 'fuschl am see',
    'grand rapids', 'rolling meadows', 'são josé dos campos',
    'palmetto', 'burlington', 'bedfordview', 'i̇stanbul',
    'cobb', 'redwood city', 'durham', 'badhoevedorp', 'costa mesa',
    'richmond', 'springfield', 'oxford', 'belfast', 'moliterno',
    'columbia', 'midrand', 'swords', 'redditch', 'monterrey',
    'hedehusene', 'westborough', 'miamisburg', 'manchester',
    'newport news', 'bristol', 'nottingham', 'new delhi',
    'corning', 'las condes', 'coraopolis', 'portland', 'bolingbrook',
    'blacksburg', 'lyon'
]

city_choices = [(city, city.title()) for city in cities]
